version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: InitDataBase
      POSTGRES_USER: grupo5
      POSTGRES_PASSWORD: Grup05
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "14321:5432"  # Mapeo del puerto 4321 de tu máquina al puerto 5432 del contenedor
    volumes:
      - ./pgdata:/var/lib/postgresql/data  # Persistencia de datos en un directorio local llamado "pgdata"
